print("Hello World")
print(1, 2, 3, 4, 5,)
print(1, 2, 3, 4, 5, sep='\t')
print(1, 2, 3, 4, 5, sep='\n')
print(1, 2, 3, 4, 5, sep='/')
print(1, 2, 3, 4, 5, sep='_')
print('Hello World\n')
print('Hello World', end='\n\n\n')
print('Hello World', end='!')
